// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: api/proxy.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Target struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Target) Reset() {
	*x = Target{}
	mi := &file_api_proxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Target) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Target) ProtoMessage() {}

func (x *Target) ProtoReflect() protoreflect.Message {
	mi := &file_api_proxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Target.ProtoReflect.Descriptor instead.
func (*Target) Descriptor() ([]byte, []int) {
	return file_api_proxy_proto_rawDescGZIP(), []int{0}
}

func (x *Target) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Target) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_api_proxy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_api_proxy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_api_proxy_proto_rawDescGZIP(), []int{1}
}

func (x *Result) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Result) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Result) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Result) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ProxyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Downstream    []*Target              `protobuf:"bytes,1,rep,name=downstream,proto3" json:"downstream,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyRequest) Reset() {
	*x = ProxyRequest{}
	mi := &file_api_proxy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyRequest) ProtoMessage() {}

func (x *ProxyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proxy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyRequest.ProtoReflect.Descriptor instead.
func (*ProxyRequest) Descriptor() ([]byte, []int) {
	return file_api_proxy_proto_rawDescGZIP(), []int{2}
}

func (x *ProxyRequest) GetDownstream() []*Target {
	if x != nil {
		return x.Downstream
	}
	return nil
}

func (x *ProxyRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ProxyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handler       string                 `protobuf:"bytes,1,opt,name=handler,proto3" json:"handler,omitempty"`
	Results       []*Result              `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyResponse) Reset() {
	*x = ProxyResponse{}
	mi := &file_api_proxy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyResponse) ProtoMessage() {}

func (x *ProxyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proxy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyResponse.ProtoReflect.Descriptor instead.
func (*ProxyResponse) Descriptor() ([]byte, []int) {
	return file_api_proxy_proto_rawDescGZIP(), []int{3}
}

func (x *ProxyResponse) GetHandler() string {
	if x != nil {
		return x.Handler
	}
	return ""
}

func (x *ProxyResponse) GetResults() []*Result {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_api_proxy_proto protoreflect.FileDescriptor

const file_api_proxy_proto_rawDesc = "" +
	"\n" +
	"\x0fapi/proxy.proto\x12\x03api\"2\n" +
	"\x06Target\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\"\\\n" +
	"\x06Result\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"U\n" +
	"\fProxyRequest\x12+\n" +
	"\n" +
	"downstream\x18\x01 \x03(\v2\v.api.TargetR\n" +
	"downstream\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"P\n" +
	"\rProxyResponse\x12\x18\n" +
	"\ahandler\x18\x01 \x01(\tR\ahandler\x12%\n" +
	"\aresults\x18\x02 \x03(\v2\v.api.ResultR\aresults2\xd9\x01\n" +
	"\fProxyService\x120\n" +
	"\aCallOne\x12\x11.api.ProxyRequest\x1a\x12.api.ProxyResponse\x120\n" +
	"\aCallTwo\x12\x11.api.ProxyRequest\x1a\x12.api.ProxyResponse\x122\n" +
	"\tCallThree\x12\x11.api.ProxyRequest\x1a\x12.api.ProxyResponse\x121\n" +
	"\bCallFour\x12\x11.api.ProxyRequest\x1a\x12.api.ProxyResponseB\x12Z\x10test-service/apib\x06proto3"

var (
	file_api_proxy_proto_rawDescOnce sync.Once
	file_api_proxy_proto_rawDescData []byte
)

func file_api_proxy_proto_rawDescGZIP() []byte {
	file_api_proxy_proto_rawDescOnce.Do(func() {
		file_api_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proxy_proto_rawDesc), len(file_api_proxy_proto_rawDesc)))
	})
	return file_api_proxy_proto_rawDescData
}

var file_api_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proxy_proto_goTypes = []any{
	(*Target)(nil),        // 0: api.Target
	(*Result)(nil),        // 1: api.Result
	(*ProxyRequest)(nil),  // 2: api.ProxyRequest
	(*ProxyResponse)(nil), // 3: api.ProxyResponse
}
var file_api_proxy_proto_depIdxs = []int32{
	0, // 0: api.ProxyRequest.downstream:type_name -> api.Target
	1, // 1: api.ProxyResponse.results:type_name -> api.Result
	2, // 2: api.ProxyService.CallOne:input_type -> api.ProxyRequest
	2, // 3: api.ProxyService.CallTwo:input_type -> api.ProxyRequest
	2, // 4: api.ProxyService.CallThree:input_type -> api.ProxyRequest
	2, // 5: api.ProxyService.CallFour:input_type -> api.ProxyRequest
	3, // 6: api.ProxyService.CallOne:output_type -> api.ProxyResponse
	3, // 7: api.ProxyService.CallTwo:output_type -> api.ProxyResponse
	3, // 8: api.ProxyService.CallThree:output_type -> api.ProxyResponse
	3, // 9: api.ProxyService.CallFour:output_type -> api.ProxyResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proxy_proto_init() }
func file_api_proxy_proto_init() {
	if File_api_proxy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proxy_proto_rawDesc), len(file_api_proxy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proxy_proto_goTypes,
		DependencyIndexes: file_api_proxy_proto_depIdxs,
		MessageInfos:      file_api_proxy_proto_msgTypes,
	}.Build()
	File_api_proxy_proto = out.File
	file_api_proxy_proto_goTypes = nil
	file_api_proxy_proto_depIdxs = nil
}
